export * from "./socials";
export { default as Line } from "./Line";
export { default as MenuIcon } from "./MenuIcon";
export { default as StarIcon } from "./StarIcon";
export { default as CloseIcon } from "./CloseIcon";
export { default as PhoneIcon } from "./PhoneIcon";
export { default as SearchIcon } from "./SearchIcon";
export { default as BanketIcon } from "./BanketIcon";
export { default as BanketIcon2 } from "./BanketIcon2";
export { default as MessageIcon } from "./MessageIcon";
export { default as ArrowUpLeftIcon } from "./ArrowUpLeftIcon";
